words:
  - axios
  - Dagre
  - deepseek
  - doubao
  - Doutput
  - Dweb
  - earendil
  - graphlib
  - HBAI
  - modelcontextprotocol
  - nodrag
  - nopan
  - notmatch
  - nowheel
  - nums
  - popconfirm
  - pxtorem
  - qwen
  - rankdir
  - Seedance
  - skus
  - tabler
  - tdesign
  - toolcall
  - minifeel
  - txtcolor
  - wechat
