import type { Express } from "express";

import route1 from "./routes/admin/models/get";
import route2 from "./routes/admin/models/save";
import route3 from "./routes/admin/providers/get";
import route4 from "./routes/admin/providers/save";
import route5 from "./routes/admin/providers/syncModels";
import route6 from "./routes/admin/providers/test";
import route7 from "./routes/agent";
import route8 from "./routes/agent/answer";
import route9 from "./routes/agent/canvasResult";
import route10 from "./routes/agent/create";
import route11 from "./routes/agent/get";
import route12 from "./routes/agent/list";
import route13 from "./routes/agent/message";
import route14 from "./routes/agent/rename";
import route15 from "./routes/agent/skills";
import route16 from "./routes/agents/a2a/get";
import route17 from "./routes/agents/a2a/save";
import route18 from "./routes/agents/connect";
import route19 from "./routes/agents/get";
import route20 from "./routes/agents/install";
import route21 from "./routes/agents/read";
import route22 from "./routes/agents/save";
import route23 from "./routes/agents/setEnabled";
import route24 from "./routes/agents/uninstall";
import route25 from "./routes/ai/generate";
import route26 from "./routes/ai/media/generate";
import route27 from "./routes/ai/media/models";
import route28 from "./routes/ai/models";
import route29 from "./routes/assets/list";
import route30 from "./routes/assets/mkdir";
import route31 from "./routes/assets/read";
import route32 from "./routes/assets/remove";
import route33 from "./routes/assets/rename";
import route34 from "./routes/assets/save";
import route35 from "./routes/auth/google";
import route36 from "./routes/auth/logout";
import route37 from "./routes/auth/me";
import route38 from "./routes/auth/options";
import route39 from "./routes/auth/password";
import route40 from "./routes/auth/passwordReset";
import route41 from "./routes/auth/passwordSet";
import route42 from "./routes/auth/phone";
import route43 from "./routes/auth/requestCode";
import route44 from "./routes/auth/sessions/get";
import route45 from "./routes/auth/sessions/revoke";
import route46 from "./routes/desktop/clipboard/read";
import route47 from "./routes/desktop/clipboard/write";
import route48 from "./routes/desktop/devtools";
import route49 from "./routes/desktop/openUrl";
import route50 from "./routes/desktop/plugins/install";
import route51 from "./routes/desktop/providerFile/read";
import route52 from "./routes/desktop/providerFile/select";
import route53 from "./routes/desktop/ready";
import route54 from "./routes/desktop/saveFile";
import route55 from "./routes/desktop/selectDirectory";
import route56 from "./routes/desktop/selectSaveFile";
import route57 from "./routes/desktop/update/apply";
import route58 from "./routes/desktop/update/check";
import route59 from "./routes/desktop/update/download";
import route60 from "./routes/desktop/update/index";
import route61 from "./routes/ffmpeg/cancel";
import route62 from "./routes/ffmpeg/download";
import route63 from "./routes/ffmpeg/events";
import route64 from "./routes/ffmpeg/execute";
import route65 from "./routes/ffmpeg/progress";
import route66 from "./routes/ffmpeg/status";
import route67 from "./routes/generation/cancel";
import route68 from "./routes/generation/create";
import route69 from "./routes/generation/events";
import route70 from "./routes/generation/get";
import route71 from "./routes/generation/list";
import route72 from "./routes/mcp/control/events";
import route73 from "./routes/mcp/control/result";
import route74 from "./routes/mcp/control/state";
import route75 from "./routes/mcp/skill";
import route76 from "./routes/mcp/status";
import route77 from "./routes/models/get";
import route78 from "./routes/nodes/files";
import route79 from "./routes/nodes/get";
import route80 from "./routes/nodes/install";
import route81 from "./routes/nodes/save";
import route82 from "./routes/nodes/setEnabled";
import route83 from "./routes/nodes/uninstall";
import route84 from "./routes/plugins/export";
import route85 from "./routes/projects/archive";
import route86 from "./routes/projects/create";
import route87 from "./routes/projects/get";
import route88 from "./routes/projects/list";
import route89 from "./routes/projects/update";
import route90 from "./routes/providers/debug/inspect";
import route91 from "./routes/providers/debug/run";
import route92 from "./routes/providers/media/add";
import route93 from "./routes/providers/media/delete";
import route94 from "./routes/providers/media/list";
import route95 from "./routes/providers/media/models";
import route96 from "./routes/providers/media/save";
import route97 from "./routes/providers/models";
import route98 from "./routes/settings/get";
import route99 from "./routes/settings/personalization/get";
import route100 from "./routes/settings/personalization/save";
import route101 from "./routes/settings/save";
import route102 from "./routes/settings/systemPrompt";
import route103 from "./routes/skills/create";
import route104 from "./routes/skills/get";
import route105 from "./routes/skills/install";
import route106 from "./routes/skills/list";
import route107 from "./routes/skills/move";
import route108 from "./routes/skills/order";
import route109 from "./routes/skills/read";
import route110 from "./routes/skills/save";
import route111 from "./routes/skills/uninstall";
import route112 from "./routes/tools/client";
import route113 from "./routes/tools/get";
import route114 from "./routes/tools/install";
import route115 from "./routes/tools/renderers";
import route116 from "./routes/tools/save";
import route117 from "./routes/tools/setEnabled";
import route118 from "./routes/tools/uninstall";
import route119 from "./routes/workspaces/check";
import route120 from "./routes/workspaces/files/list";
import route121 from "./routes/workspaces/files/mkdir";
import route122 from "./routes/workspaces/files/read";
import route123 from "./routes/workspaces/files/remove";
import route124 from "./routes/workspaces/files/rename";
import route125 from "./routes/workspaces/files/write";
import route126 from "./routes/workspaces/list";
import route127 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/admin/models/get", route1);
  app.use("/api/admin/models/save", route2);
  app.use("/api/admin/providers/get", route3);
  app.use("/api/admin/providers/save", route4);
  app.use("/api/admin/providers/syncModels", route5);
  app.use("/api/admin/providers/test", route6);
  app.use("/api/agent", route7);
  app.use("/api/agent/answer", route8);
  app.use("/api/agent/canvasResult", route9);
  app.use("/api/agent/create", route10);
  app.use("/api/agent/get", route11);
  app.use("/api/agent/list", route12);
  app.use("/api/agent/message", route13);
  app.use("/api/agent/rename", route14);
  app.use("/api/agent/skills", route15);
  app.use("/api/agents/a2a/get", route16);
  app.use("/api/agents/a2a/save", route17);
  app.use("/api/agents/connect", route18);
  app.use("/api/agents/get", route19);
  app.use("/api/agents/install", route20);
  app.use("/api/agents/read", route21);
  app.use("/api/agents/save", route22);
  app.use("/api/agents/setEnabled", route23);
  app.use("/api/agents/uninstall", route24);
  app.use("/api/ai/generate", route25);
  app.use("/api/ai/media/generate", route26);
  app.use("/api/ai/media/models", route27);
  app.use("/api/ai/models", route28);
  app.use("/api/assets/list", route29);
  app.use("/api/assets/mkdir", route30);
  app.use("/api/assets/read", route31);
  app.use("/api/assets/remove", route32);
  app.use("/api/assets/rename", route33);
  app.use("/api/assets/save", route34);
  app.use("/api/auth/google", route35);
  app.use("/api/auth/logout", route36);
  app.use("/api/auth/me", route37);
  app.use("/api/auth/options", route38);
  app.use("/api/auth/password", route39);
  app.use("/api/auth/passwordReset", route40);
  app.use("/api/auth/passwordSet", route41);
  app.use("/api/auth/phone", route42);
  app.use("/api/auth/requestCode", route43);
  app.use("/api/auth/sessions/get", route44);
  app.use("/api/auth/sessions/revoke", route45);
  app.use("/api/desktop/clipboard/read", route46);
  app.use("/api/desktop/clipboard/write", route47);
  app.use("/api/desktop/devtools", route48);
  app.use("/api/desktop/openUrl", route49);
  app.use("/api/desktop/plugins/install", route50);
  app.use("/api/desktop/providerFile/read", route51);
  app.use("/api/desktop/providerFile/select", route52);
  app.use("/api/desktop/ready", route53);
  app.use("/api/desktop/saveFile", route54);
  app.use("/api/desktop/selectDirectory", route55);
  app.use("/api/desktop/selectSaveFile", route56);
  app.use("/api/desktop/update/apply", route57);
  app.use("/api/desktop/update/check", route58);
  app.use("/api/desktop/update/download", route59);
  app.use("/api/desktop/update", route60);
  app.use("/api/ffmpeg/cancel", route61);
  app.use("/api/ffmpeg/download", route62);
  app.use("/api/ffmpeg/events", route63);
  app.use("/api/ffmpeg/execute", route64);
  app.use("/api/ffmpeg/progress", route65);
  app.use("/api/ffmpeg/status", route66);
  app.use("/api/generation/cancel", route67);
  app.use("/api/generation/create", route68);
  app.use("/api/generation/events", route69);
  app.use("/api/generation/get", route70);
  app.use("/api/generation/list", route71);
  app.use("/api/mcp/control/events", route72);
  app.use("/api/mcp/control/result", route73);
  app.use("/api/mcp/control/state", route74);
  app.use("/api/mcp/skill", route75);
  app.use("/api/mcp/status", route76);
  app.use("/api/models/get", route77);
  app.use("/api/nodes/files", route78);
  app.use("/api/nodes/get", route79);
  app.use("/api/nodes/install", route80);
  app.use("/api/nodes/save", route81);
  app.use("/api/nodes/setEnabled", route82);
  app.use("/api/nodes/uninstall", route83);
  app.use("/api/plugins/export", route84);
  app.use("/api/projects/archive", route85);
  app.use("/api/projects/create", route86);
  app.use("/api/projects/get", route87);
  app.use("/api/projects/list", route88);
  app.use("/api/projects/update", route89);
  app.use("/api/providers/debug/inspect", route90);
  app.use("/api/providers/debug/run", route91);
  app.use("/api/providers/media/add", route92);
  app.use("/api/providers/media/delete", route93);
  app.use("/api/providers/media/list", route94);
  app.use("/api/providers/media/models", route95);
  app.use("/api/providers/media/save", route96);
  app.use("/api/providers/models", route97);
  app.use("/api/settings/get", route98);
  app.use("/api/settings/personalization/get", route99);
  app.use("/api/settings/personalization/save", route100);
  app.use("/api/settings/save", route101);
  app.use("/api/settings/systemPrompt", route102);
  app.use("/api/skills/create", route103);
  app.use("/api/skills/get", route104);
  app.use("/api/skills/install", route105);
  app.use("/api/skills/list", route106);
  app.use("/api/skills/move", route107);
  app.use("/api/skills/order", route108);
  app.use("/api/skills/read", route109);
  app.use("/api/skills/save", route110);
  app.use("/api/skills/uninstall", route111);
  app.use("/api/tools/client", route112);
  app.use("/api/tools/get", route113);
  app.use("/api/tools/install", route114);
  app.use("/api/tools/renderers", route115);
  app.use("/api/tools/save", route116);
  app.use("/api/tools/setEnabled", route117);
  app.use("/api/tools/uninstall", route118);
  app.use("/api/workspaces/check", route119);
  app.use("/api/workspaces/files/list", route120);
  app.use("/api/workspaces/files/mkdir", route121);
  app.use("/api/workspaces/files/read", route122);
  app.use("/api/workspaces/files/remove", route123);
  app.use("/api/workspaces/files/rename", route124);
  app.use("/api/workspaces/files/write", route125);
  app.use("/api/workspaces/list", route126);
  app.use("/api/workspaces/selectDirectory", route127);
}
