import type { Express } from "express";

import route1 from "./routes/account/get";
import route2 from "./routes/admin/audit/get";
import route3 from "./routes/admin/dashboard/get";
import route4 from "./routes/admin/models/get";
import route5 from "./routes/admin/models/save";
import route6 from "./routes/admin/projects/open";
import route7 from "./routes/admin/providers/get";
import route8 from "./routes/admin/providers/save";
import route9 from "./routes/admin/providers/syncModels";
import route10 from "./routes/admin/providers/test";
import route11 from "./routes/admin/tasks/get";
import route12 from "./routes/admin/users/get";
import route13 from "./routes/admin/users/grantCredits";
import route14 from "./routes/admin/users/revokeSession";
import route15 from "./routes/admin/users/update";
import route16 from "./routes/agent";
import route17 from "./routes/agent/answer";
import route18 from "./routes/agent/canvasResult";
import route19 from "./routes/agent/create";
import route20 from "./routes/agent/get";
import route21 from "./routes/agent/list";
import route22 from "./routes/agent/message";
import route23 from "./routes/agent/rename";
import route24 from "./routes/agent/skills";
import route25 from "./routes/agents/a2a/get";
import route26 from "./routes/agents/a2a/save";
import route27 from "./routes/agents/get";
import route28 from "./routes/agents/install";
import route29 from "./routes/agents/read";
import route30 from "./routes/agents/save";
import route31 from "./routes/agents/setEnabled";
import route32 from "./routes/agents/uninstall";
import route33 from "./routes/ai/generate";
import route34 from "./routes/ai/media/generate";
import route35 from "./routes/ai/media/models";
import route36 from "./routes/ai/models";
import route37 from "./routes/assets/list";
import route38 from "./routes/assets/mkdir";
import route39 from "./routes/assets/read";
import route40 from "./routes/assets/remove";
import route41 from "./routes/assets/rename";
import route42 from "./routes/assets/save";
import route43 from "./routes/auth/google";
import route44 from "./routes/auth/logout";
import route45 from "./routes/auth/me";
import route46 from "./routes/auth/options";
import route47 from "./routes/auth/password";
import route48 from "./routes/auth/passwordReset";
import route49 from "./routes/auth/passwordSet";
import route50 from "./routes/auth/phone";
import route51 from "./routes/auth/requestCode";
import route52 from "./routes/auth/sessions/get";
import route53 from "./routes/auth/sessions/revoke";
import route54 from "./routes/ffmpeg/execute";
import route55 from "./routes/ffmpeg/status";
import route56 from "./routes/generation/cancel";
import route57 from "./routes/generation/create";
import route58 from "./routes/generation/events";
import route59 from "./routes/generation/get";
import route60 from "./routes/generation/list";
import route61 from "./routes/mcp/control/events";
import route62 from "./routes/mcp/control/result";
import route63 from "./routes/mcp/control/state";
import route64 from "./routes/mcp/skill";
import route65 from "./routes/mcp/status";
import route66 from "./routes/models/get";
import route67 from "./routes/myAssets/list";
import route68 from "./routes/myAssets/mkdir";
import route69 from "./routes/myAssets/read";
import route70 from "./routes/myAssets/remove";
import route71 from "./routes/myAssets/rename";
import route72 from "./routes/myAssets/save";
import route73 from "./routes/nodes/files";
import route74 from "./routes/nodes/get";
import route75 from "./routes/nodes/install";
import route76 from "./routes/nodes/save";
import route77 from "./routes/nodes/setEnabled";
import route78 from "./routes/nodes/uninstall";
import route79 from "./routes/plugins/export";
import route80 from "./routes/projects/archive";
import route81 from "./routes/projects/create";
import route82 from "./routes/projects/get";
import route83 from "./routes/projects/legacy/get";
import route84 from "./routes/projects/legacy/import";
import route85 from "./routes/projects/list";
import route86 from "./routes/projects/update";
import route87 from "./routes/settings/get";
import route88 from "./routes/settings/personalization/get";
import route89 from "./routes/settings/personalization/save";
import route90 from "./routes/settings/save";
import route91 from "./routes/settings/systemPrompt";
import route92 from "./routes/skills/create";
import route93 from "./routes/skills/get";
import route94 from "./routes/skills/install";
import route95 from "./routes/skills/list";
import route96 from "./routes/skills/move";
import route97 from "./routes/skills/order";
import route98 from "./routes/skills/read";
import route99 from "./routes/skills/save";
import route100 from "./routes/skills/uninstall";
import route101 from "./routes/tools/client";
import route102 from "./routes/tools/get";
import route103 from "./routes/tools/install";
import route104 from "./routes/tools/renderers";
import route105 from "./routes/tools/save";
import route106 from "./routes/tools/setEnabled";
import route107 from "./routes/tools/uninstall";
import route108 from "./routes/workspaces/check";
import route109 from "./routes/workspaces/files/list";
import route110 from "./routes/workspaces/files/mkdir";
import route111 from "./routes/workspaces/files/read";
import route112 from "./routes/workspaces/files/remove";
import route113 from "./routes/workspaces/files/rename";
import route114 from "./routes/workspaces/files/write";
import route115 from "./routes/workspaces/list";
import route116 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/account/get", route1);
  app.use("/api/admin/audit/get", route2);
  app.use("/api/admin/dashboard/get", route3);
  app.use("/api/admin/models/get", route4);
  app.use("/api/admin/models/save", route5);
  app.use("/api/admin/projects/open", route6);
  app.use("/api/admin/providers/get", route7);
  app.use("/api/admin/providers/save", route8);
  app.use("/api/admin/providers/syncModels", route9);
  app.use("/api/admin/providers/test", route10);
  app.use("/api/admin/tasks/get", route11);
  app.use("/api/admin/users/get", route12);
  app.use("/api/admin/users/grantCredits", route13);
  app.use("/api/admin/users/revokeSession", route14);
  app.use("/api/admin/users/update", route15);
  app.use("/api/agent", route16);
  app.use("/api/agent/answer", route17);
  app.use("/api/agent/canvasResult", route18);
  app.use("/api/agent/create", route19);
  app.use("/api/agent/get", route20);
  app.use("/api/agent/list", route21);
  app.use("/api/agent/message", route22);
  app.use("/api/agent/rename", route23);
  app.use("/api/agent/skills", route24);
  app.use("/api/agents/a2a/get", route25);
  app.use("/api/agents/a2a/save", route26);
  app.use("/api/agents/get", route27);
  app.use("/api/agents/install", route28);
  app.use("/api/agents/read", route29);
  app.use("/api/agents/save", route30);
  app.use("/api/agents/setEnabled", route31);
  app.use("/api/agents/uninstall", route32);
  app.use("/api/ai/generate", route33);
  app.use("/api/ai/media/generate", route34);
  app.use("/api/ai/media/models", route35);
  app.use("/api/ai/models", route36);
  app.use("/api/assets/list", route37);
  app.use("/api/assets/mkdir", route38);
  app.use("/api/assets/read", route39);
  app.use("/api/assets/remove", route40);
  app.use("/api/assets/rename", route41);
  app.use("/api/assets/save", route42);
  app.use("/api/auth/google", route43);
  app.use("/api/auth/logout", route44);
  app.use("/api/auth/me", route45);
  app.use("/api/auth/options", route46);
  app.use("/api/auth/password", route47);
  app.use("/api/auth/passwordReset", route48);
  app.use("/api/auth/passwordSet", route49);
  app.use("/api/auth/phone", route50);
  app.use("/api/auth/requestCode", route51);
  app.use("/api/auth/sessions/get", route52);
  app.use("/api/auth/sessions/revoke", route53);
  app.use("/api/ffmpeg/execute", route54);
  app.use("/api/ffmpeg/status", route55);
  app.use("/api/generation/cancel", route56);
  app.use("/api/generation/create", route57);
  app.use("/api/generation/events", route58);
  app.use("/api/generation/get", route59);
  app.use("/api/generation/list", route60);
  app.use("/api/mcp/control/events", route61);
  app.use("/api/mcp/control/result", route62);
  app.use("/api/mcp/control/state", route63);
  app.use("/api/mcp/skill", route64);
  app.use("/api/mcp/status", route65);
  app.use("/api/models/get", route66);
  app.use("/api/myAssets/list", route67);
  app.use("/api/myAssets/mkdir", route68);
  app.use("/api/myAssets/read", route69);
  app.use("/api/myAssets/remove", route70);
  app.use("/api/myAssets/rename", route71);
  app.use("/api/myAssets/save", route72);
  app.use("/api/nodes/files", route73);
  app.use("/api/nodes/get", route74);
  app.use("/api/nodes/install", route75);
  app.use("/api/nodes/save", route76);
  app.use("/api/nodes/setEnabled", route77);
  app.use("/api/nodes/uninstall", route78);
  app.use("/api/plugins/export", route79);
  app.use("/api/projects/archive", route80);
  app.use("/api/projects/create", route81);
  app.use("/api/projects/get", route82);
  app.use("/api/projects/legacy/get", route83);
  app.use("/api/projects/legacy/import", route84);
  app.use("/api/projects/list", route85);
  app.use("/api/projects/update", route86);
  app.use("/api/settings/get", route87);
  app.use("/api/settings/personalization/get", route88);
  app.use("/api/settings/personalization/save", route89);
  app.use("/api/settings/save", route90);
  app.use("/api/settings/systemPrompt", route91);
  app.use("/api/skills/create", route92);
  app.use("/api/skills/get", route93);
  app.use("/api/skills/install", route94);
  app.use("/api/skills/list", route95);
  app.use("/api/skills/move", route96);
  app.use("/api/skills/order", route97);
  app.use("/api/skills/read", route98);
  app.use("/api/skills/save", route99);
  app.use("/api/skills/uninstall", route100);
  app.use("/api/tools/client", route101);
  app.use("/api/tools/get", route102);
  app.use("/api/tools/install", route103);
  app.use("/api/tools/renderers", route104);
  app.use("/api/tools/save", route105);
  app.use("/api/tools/setEnabled", route106);
  app.use("/api/tools/uninstall", route107);
  app.use("/api/workspaces/check", route108);
  app.use("/api/workspaces/files/list", route109);
  app.use("/api/workspaces/files/mkdir", route110);
  app.use("/api/workspaces/files/read", route111);
  app.use("/api/workspaces/files/remove", route112);
  app.use("/api/workspaces/files/rename", route113);
  app.use("/api/workspaces/files/write", route114);
  app.use("/api/workspaces/list", route115);
  app.use("/api/workspaces/selectDirectory", route116);
}
