/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/settings/panels/about.vue')['default']
    Agent: typeof import('./../components/agent/index.vue')['default']
    AttachmentList: typeof import('./../components/agent/attachmentList.vue')['default']
    AttachmentPreview: typeof import('./../components/agent/attachmentPreview.vue')['default']
    CanvasShortcuts: typeof import('./../components/settings/panels/general/canvasShortcuts.vue')['default']
    Conversation: typeof import('./../components/agent/conversation.vue')['default']
    Developer: typeof import('./../components/settings/panels/developer/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    General: typeof import('./../components/settings/panels/general/index.vue')['default']
    IconArrowGuide: typeof import('@tabler/icons-vue')['IconArrowGuide']
    IconBorderRadius: typeof import('@tabler/icons-vue')['IconBorderRadius']
    IconFolders: typeof import('@tabler/icons-vue')['IconFolders']
    IconSitemap: typeof import('@tabler/icons-vue')['IconSitemap']
    IconTextSize: typeof import('@tabler/icons-vue')['IconTextSize']
    KeyInput: typeof import('./../components/settings/panels/general/keyInput.vue')['default']
    MarkdownImage: typeof import('./../components/markdownImage.vue')['default']
    Mcp: typeof import('./../components/settings/panels/mcp/index.vue')['default']
    MediaToolDialog: typeof import('./../components/agent/mediaToolDialog.vue')['default']
    Menu: typeof import('./../components/agent/menu.vue')['default']
    MessageMarkdown: typeof import('./../components/messageMarkdown.vue')['default']
    ModelPopover: typeof import('./../components/modelPopover.vue')['default']
    Personalization: typeof import('./../components/settings/panels/personalization.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../components/settings/index.vue')['default']
    SkillMenu: typeof import('./../components/agent/skillMenu.vue')['default']
    ToolMessage: typeof import('./../components/agent/toolMessage.vue')['default']
    Ui: typeof import('./../components/settings/panels/ui.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
